### ISSUE TITLE
Dynamic input

### ISSUE THREAD

**Issue by himanshuraja** [ethanped/BlackHatPythonPractice#1]
It will be good if we can take input of host using raw_input() and port using int(raw_input()) or using input() method.

**Comment by ethanped** [comment]
You can actually pass these in as parameters when initializing the client. One thing that could be done though is to add a function that lets a user change the target host/port

**Comment by himanshuraja** [comment]
yes,for sure,and can I add other scripts into it?for port-scanning ?

**Comment by ethanped** [comment]
Of course, go right ahead! I will hopefully add more scripts here soon as well
